### ISSUE TITLE
Bug Report: problems compiling 

### ISSUE THREAD

**Issue by ghost** [KadeDev/Vs-Zardy#1]
i cant complie because it give a lua error please fix it

**Comment by Sendan4** [comment]
is this?

![imagen](https://user-images.githubusercontent.com/60526375/132074560-5d044d63-7d92-4c6b-b361-510aa10b922d.png)

**Comment by ghost** [comment]
oh yeah

**Comment by ghost** [comment]
how do you fix?

**Comment by Sendan4** [comment]
The truth is that I don't know yet, it happens in several versions of Kade engine, some old and some new.

**Comment by Sendan4** [comment]
I would like to use this version that uses this mod (1.7), since modcharts work beyond windows. but this stops me.

**Comment by TheRealJake12** [comment]
> I would like to use this version that uses this mod (1.7), since modcharts work beyond windows. but this stops me.

haxelib remove linc_luajit

haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit 0af04cd3a1

haxelib remove polymod

haxelib git polymod https://github.com/MasterEric/polymod

the polymod fixes a crash when its caching.
