### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by JTrulz** [KadeDev/Vs-Zardy#2]
Windows 10 64 bit
0.2.7.1 FNF - 1.7 Kade Engine (Most recent Zardy release)

Game is locked to somewhere around 60fps (I cant tell exactly what the frame rate is but its definitely lower than 120, although the fps display still claims the game to be at 126 or whatever i set it to in the settings.)
I do not have this problem with other mods nor older releases of Kade engine, however the newest release (1.7 as of this report) does retain this problem

Kade Engine 1.6.2 does not have this issue

Thank you in advance and keep up the good work KadeDev I love your shit

**Comment by foxcool119** [comment]
bruh when i put the b side mod into kade engine 1.7 this happens it takes me to the wrong stages 
![image](https://user-images.githubusercontent.com/89747510/131475973-2ab976ec-166a-4afd-8a5a-8585fa90d643.png)

**Comment by iamteles** [comment]
I have this same bug, where the notes seem to scroll at a lower framerate as the rest of the game.

**Comment by iamteles** [comment]
Ok, so i did some research and this bug is now fixed in kade engine but im not sure if kade will update the mod with the new kade engine version

**Comment by Kade-github** [comment]
fixed

**Comment by JTrulz** [comment]
the latest zardy release still has this problem is there anything I can do to port zardy into the updated kade engine?
